<template>
  <q-page class="">
    <h3 class="text-center">About</h3>

    <div class="q-ml-md q-mr-md">
      <p>Nascetur commodo consequat eleifend proin aenean non nisi mus quam pellentesque augue, efficitur massa primis ac enim rhoncus nullam facilisi a consectetur ornare mollis, pulvinar etiam facilisis hendrerit eros nunc inceptos leo montes blandit. Mi etiam imperdiet odio hac tempor lectus finibus torquent euismod risus class, curabitur integer praesent ad gravida quisque facilisi dapibus turpis justo porta, metus sapien sagittis litora a ut sit venenatis quam maecenas. Fringilla accumsan purus potenti erat conubia sit himenaeos, est volutpat dignissim ipsum dapibus ridiculus, ligula nec non fusce maecenas curae.</p>
      <p>Ante magnis fermentum facilisis facilisi in torquent sapien leo aenean, massa mattis velit nam justo rhoncus netus neque mi viverra, efficitur suspendisse tempus faucibus potenti penatibus dictum eget. Congue varius sem risus imperdiet primis etiam orci vitae facilisis, interdum libero lectus potenti euismod justo tellus sollicitudin, ridiculus fusce montes fringilla tortor feugiat convallis nisi. Dolor habitasse fringilla vitae lorem auctor per diam porta est ultrices donec, inceptos rutrum arcu ligula suspendisse parturient libero maximus maecenas eleifend, cras commodo ullamcorper at efficitur ornare augue consequat primis velit. Maecenas elit montes potenti dui ornare lacus inceptos bibendum iaculis, facilisis aliquam cras massa magnis eros sem fusce erat fringilla, cubilia aenean scelerisque nullam euismod convallis consequat tempor.</p>
      <p>Dui ridiculus justo neque facilisi iaculis porta, adipiscing nostra feugiat hendrerit quam, class nulla rutrum nisi nascetur sapien, massa ullamcorper tellus vitae. Morbi consectetur habitant mi fames aliquam, lacinia feugiat ante torquent risus erat, sociosqu montes rutrum nibh. Dictumst ex eleifend duis fermentum volutpat imperdiet vivamus, integer urna sem potenti a sit vitae enim, finibus amet magna dapibus ipsum euismod. Nascetur nec augue sem imperdiet platea eleifend vitae facilisis, nisl morbi blandit dui lacus luctus magnis, fames pulvinar penatibus arcu curae ante praesent. Habitant imperdiet fusce at nulla velit nascetur risus nunc, ante rhoncus tempus netus ad senectus odio, litora diam morbi nam vivamus magnis curae. Fermentum elit pellentesque consequat orci vestibulum augue velit convallis, litora quis nulla finibus nullam morbi curabitur commodo, condimentum quisque parturient accumsan vehicula laoreet nec. Ullamcorper praesent maximus velit non feugiat lacus nunc neque parturient class massa conubia sollicitudin interdum urna, tempor diam commodo consectetur at a netus efficitur vel ultrices lectus elementum volutpat. Efficitur mollis lectus curabitur leo justo consequat massa fermentum sed nulla, nec libero curae non dictum habitant nostra luctus erat lorem euismod, quis phasellus suspendisse diam parturient accumsan inceptos pharetra ex.</p>
      <p>Ridiculus tellus praesent blandit nascetur dignissim vestibulum iaculis ac eleifend fames, etiam odio ipsum finibus fusce bibendum purus nibh eget diam, malesuada mus cubilia libero justo sociosqu eu quam mauris. Interdum tempus pellentesque porta accumsan mus molestie sed torquent justo tempor inceptos, libero donec class est magnis morbi quis mattis eget maximus, potenti rutrum vehicula non dapibus praesent eu consequat habitasse aliquam. Conubia accumsan vestibulum dictumst aliquam eget litora euismod montes, congue magna fames duis cras primis fermentum mi, libero enim rutrum ac placerat fusce scelerisque. Proin nam magnis integer metus tincidunt nec placerat imperdiet bibendum tellus, eros suscipit suspendisse maximus lacinia morbi rutrum dolor primis penatibus blandit, elementum et malesuada turpis porttitor massa tempus fusce ut. Tellus sit finibus arcu suscipit tempor praesent ligula leo proin neque faucibus lorem pretium inceptos sagittis eu magna, scelerisque viverra facilisis montes fermentum ad dictumst tincidunt dignissim imperdiet in gravida etiam est sem. Pretium lorem lacus mi suscipit facilisi dictumst quisque mattis litora, congue fusce a ultricies finibus integer praesent venenatis ad ex, id enim sollicitudin augue montes nisl vel vehicula. Pretium amet quam a varius sit luctus laoreet penatibus tortor gravida at dictum, leo nibh facilisis ad faucibus pellentesque magnis venenatis dis efficitur sem.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipiscing, elit mauris non consequat dictum suscipit, sem dapibus luctus ex magnis. Cubilia aliquet blandit fringilla neque id nascetur luctus, sit donec cras vitae facilisis suspendisse amet laoreet, quisque vivamus scelerisque faucibus integer tempor. Arcu proin sociosqu montes fringilla potenti suspendisse penatibus duis libero, rhoncus ipsum dignissim hendrerit fermentum per donec vivamus, id ullamcorper etiam vehicula pharetra orci nullam maecenas. Auctor vestibulum eu adipiscing at orci et aliquam molestie sociosqu sed torquent, quis dolor sem ridiculus vehicula curae dapibus mauris donec himenaeos, aptent pharetra lacus suspendisse nisl bibendum proin duis iaculis tortor. Convallis scelerisque maximus in sollicitudin penatibus nullam facilisi, non posuere nisi ornare morbi iaculis nisl, finibus bibendum dignissim primis condimentum cras. Eros varius mauris curabitur magna posuere suspendisse sed tristique ad nibh, urna eu enim vel imperdiet integer ridiculus nisi morbi odio, nunc potenti duis rutrum condimentum mus orci ullamcorper class.</p>
    </div>
  </q-page>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'About'
})
</script>
